name: explore_academy_superadmin
description: An explore academy  super admin applicadtion.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  http:
  intl:
  file_picker:
  encrypt:
  shared_preferences:
  flutter_typeahead:
  percent_indicator:
  fl_chart:
  syncfusion_flutter_charts:
  syncfusion_flutter_xlsio:
  path_provider:
  path_provider_windows:
  open_file: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
